version: "3"

includes:
  compose:
    taskfile: TaskfileCompose.yml
  mysql:
    taskfile: TaskfileMySQL.yml

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none
